name: Deploy
on:
  release:
    types: [created]

jobs:
  package:
    name: 🚀 Publish Package
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: https://npm.pkg.github.com/
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
          NODE_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: 📖 Deploy Documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: https://npm.pkg.github.com/
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
          NODE_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
      - run: npm run build-storybook
      - name: Deploy Docs 📖
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
